"""Build the portable light presentation viewer."""
from pathlib import Path
import json
import shutil

from story import SL, SOURCES

ROOT = Path(__file__).resolve().parents[1]
out = ROOT / "website-bundle"
out.mkdir(exist_ok=True)
for folder in ("media", "downloads", "slides"):
    (out / folder).mkdir(exist_ok=True)
for p in (ROOT / "media").glob("*"):
    if p.is_file() and p.suffix in (".mp4", ".gif", ".png"):
        shutil.copy2(p, out / "media" / p.name)
for suffix in (".pdf", ".pptx"):
    name = "iff-visual-showcase" + suffix
    shutil.copy2(ROOT / "build" / name, out / "downloads" / name)
shutil.copy2(ROOT / "build" / "cover.png", out / "cover.png")
for p in (ROOT / "build" / "slides").glob("*.svg"):
    shutil.copy2(p, out / "slides" / p.name)
data=[]
for i,d in enumerate(SL):
 data.append({'number':i+1,'title':d['title'],'chapter':d['chapter'],'lead':d['lead'],'notes':d['notes'].split('\n\nReadable equations and values:')[0],'text_equivalents':d.get('text_equivalents',[]),'media':d['media'],'sources':[{'title':SOURCES[r]['title'],'url':SOURCES[r]['url'],'scope':SOURCES[r]['scope']} for r in d['refs']]})
js=json.dumps(data,ensure_ascii=False).replace('</','<\\/')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Interface Force Field: From atoms to evidence</title><style>
:root{color-scheme:light;--bg:#FBFAF7;--fg:#1B1B1A;--mut:#5C5A55;--teal:#166D66;--gold:#80530C;--blue:#315FA2;--red:#A23447;--card:#F3F0E8;--rule:#E3DFD6;--border:#B9B3A5}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.5 system-ui,sans-serif}header{padding:14px 28px;display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid var(--rule)}header strong{letter-spacing:.03em}a{color:var(--teal)}nav{display:flex;flex-wrap:wrap;align-items:center;justify-content:center;gap:10px;padding:14px}button,select{font:inherit;background:var(--card);color:var(--fg);border:1px solid var(--border);padding:8px 12px;border-radius:6px}button:hover{border-color:var(--teal)}button:focus-visible,a:focus-visible,select:focus-visible{outline:3px solid var(--teal);outline-offset:3px}button:disabled{opacity:.4}main{max-width:1400px;margin:auto;padding:0 20px}#stage{touch-action:pan-y;aspect-ratio:16/9;position:relative;background:var(--bg);border:1px solid var(--rule)}#slide{width:100%;height:100%;display:block}#caption{padding:10px 0;color:var(--mut);display:flex;justify-content:space-between;gap:16px}#notes{padding:20px 24px;background:var(--card);margin:14px 0 24px;border-radius:8px}#notes p{max-width:1050px;white-space:pre-line;overflow-wrap:anywhere}#notes li{overflow-wrap:anywhere}#notes ul{padding-left:20px}#notes li{margin:12px 0}#notes small{display:block;color:var(--mut)}details{border-top:1px solid var(--rule);margin:20px 0;padding:16px 0}summary{cursor:pointer;color:var(--teal)}.media-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:20px 0}.media-grid video{width:100%;aspect-ratio:16/9}.media-card{padding:12px;background:var(--card);border-radius:8px}.media-card p{font-size:14px;color:var(--mut)}dialog{max-width:1100px;width:94vw;background:var(--bg);color:var(--fg);border:1px solid var(--border);padding:20px}dialog::backdrop{background:#000b}dialog video{width:100%;display:block;margin:16px 0}dialog button{float:right}footer{padding:25px 28px;color:var(--mut);font-size:13px;border-top:1px solid var(--rule)}.top-links{display:flex;gap:18px}#counter{min-width:70px;text-align:center}body.present header,body.present #caption,body.present #notes,body.present details,body.present footer{display:none}body.present main{max-width:none;padding:0}body.present #stage{max-height:calc(100vh - 75px);max-width:calc((100vh - 75px)*16/9);margin:auto} @media(max-width:720px){header{padding:12px 16px;display:block}header .top-links{margin-top:8px}main{padding:0 8px}nav{padding:10px 6px;gap:6px}select{max-width:46vw;font-size:13px}#notes{padding:14px}#caption{font-size:13px}.media-grid{grid-template-columns:1fr}}@media print{header,nav,details,dialog,footer,#caption{display:none}main{max-width:none;padding:0}#stage{border:none}#notes{background:white;color:black}a{color:black}}
</style></head><body><header><strong>INTERFACE FORCE FIELD <span style="color:var(--mut)">/ atoms → evidence</span></strong><div class="top-links"><a href="downloads/iff-visual-showcase.pptx" download>Editable PPTX</a><a href="downloads/iff-visual-showcase.pdf" download>PDF</a></div></header><nav aria-label="Presentation navigation"><button id="prev" aria-label="Previous slide">←</button><span id="counter" aria-live="polite"></span><button id="next" aria-label="Next slide">→</button><select id="choose" aria-label="Choose a slide"></select><button id="notesBtn" aria-expanded="true">Hide notes</button><button id="mediaBtn" hidden>Play media</button><button id="present">Present</button></nav><main><div id="stage"><img id="slide" alt="" src="slides/01.svg"></div><div id="caption"><span id="lead"></span><span>← / →, swipe or choose a slide · N notes · P present</span></div><section id="notes" aria-label="Presenter explanation and source citations"></section><details><summary>Media library · MP4, GIF and static alternatives</summary><div class="media-grid">
'''
for name,title,desc in [('structure-walkthrough','Structure walkthrough','Corrected Rh geometry; camera motion only. Not a simulated material trajectory.'),('model-walkthrough','Model walkthrough','Prescribed analytical two-atom motion in reduced units. Not materials MD.'),('evidence-walkthrough','Evidence walkthrough','Published numerical comparisons followed by a hypothetical new evidence contract. No new validated revision.')]:
 page+=f'<article class="media-card"><strong>{title}</strong><video controls preload="metadata" playsinline poster="media/{name}-poster.png"><source src="media/{name}.mp4" type="video/mp4"></video><p>{desc}</p><a href="media/{name}.gif">GIF</a> · <a href="media/{name}-poster.png">Static PNG</a> · <a href="media/{name}.mp4" download>MP4</a></article>'
page+='''</div><p>All videos are silent, with visible labels. Every animation has a static alternative. Reduced-motion users receive the same static slides and can choose playback.</p></details></main><dialog id="motion"><button id="closeMotion">Close ×</button><h2 id="motionTitle"></h2><video id="player" controls playsinline preload="metadata"></video><p id="motionDesc"></p><a id="staticLink">Static alternative</a></dialog><footer>Sean Florez · prepared 3 October 2026. Literature results were not rerun here. Ideal source-derived structures and explicitly illustrative motion remain distinct from scientific simulation evidence. No new fitted or scientifically accepted parameter package is claimed. <a href="citation-license-manifest.json">Sources and reuse manifest</a></footer><script>
const slides=SLIDE_DATA;let current=0;const $=id=>document.getElementById(id);const descriptions={"structure-walkthrough":"Source-grounded ideal geometry and camera motion only.","model-walkthrough":"Prescribed analytical motion, not an IFF materials MD trajectory.","evidence-walkthrough":"Published data reveal; model revision is a hypothetical next contract, not a completed validation."};
slides.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${String(i+1).padStart(2,'0')} · ${s.title}`;$('choose').append(o)});
function show(n){current=Math.max(0,Math.min(slides.length-1,n));const s=slides[current];$('slide').src=`slides/${String(current+1).padStart(2,'0')}.svg`;$('slide').alt=`Slide ${current+1}: ${s.title}. ${s.lead}`;$('counter').textContent=`${current+1} / ${slides.length}`;$('choose').value=current;$('prev').disabled=current===0;$('next').disabled=current===slides.length-1;$('lead').textContent=s.lead;$('mediaBtn').hidden=!s.media;const section=$('notes');section.replaceChildren();const h=document.createElement('h2');h.textContent=s.title;section.append(h);const p=document.createElement('p');p.textContent=s.notes;section.append(p);if(s.text_equivalents.length){const h3=document.createElement('h3');h3.textContent='Readable equations and table values';section.append(h3);const values=document.createElement('ul');values.id='textEquivalents';s.text_equivalents.forEach(text=>{const li=document.createElement('li');li.textContent=text;values.append(li)});section.append(values)}const ul=document.createElement('ul');s.sources.forEach(src=>{const li=document.createElement('li');const a=document.createElement(src.url?'a':'span');a.textContent=src.title;if(src.url){a.href=src.url;a.target='_blank';a.rel='noopener'}li.append(a);const sm=document.createElement('small');sm.textContent=src.scope;li.append(sm);ul.append(li)});section.append(ul);history.replaceState(null,'',`#${current+1}`)}
let swipeStart=null;
$('stage').addEventListener('touchstart',e=>{if(e.touches.length!==1){swipeStart=null;return}const t=e.touches[0];swipeStart={x:t.clientX,y:t.clientY,time:performance.now()}},{passive:true});
$('stage').addEventListener('touchend',e=>{if(!swipeStart||e.changedTouches.length!==1)return;const t=e.changedTouches[0];const dx=t.clientX-swipeStart.x,dy=t.clientY-swipeStart.y;const elapsed=performance.now()-swipeStart.time;swipeStart=null;if(elapsed<1200&&Math.abs(dx)>=45&&Math.abs(dx)>Math.abs(dy)*1.4)show(current+(dx<0?1:-1))},{passive:true});
$('stage').addEventListener('touchcancel',()=>{swipeStart=null},{passive:true});
$('prev').onclick=()=>show(current-1);$('next').onclick=()=>show(current+1);$('choose').onchange=e=>show(+e.target.value);$('notesBtn').onclick=()=>{const n=$('notes');n.hidden=!n.hidden;$('notesBtn').textContent=n.hidden?'Show notes':'Hide notes';$('notesBtn').setAttribute('aria-expanded',String(!n.hidden))};$('present').onclick=()=>{document.body.classList.toggle('present');$('present').textContent=document.body.classList.contains('present')?'Exit present':'Present'};$('mediaBtn').onclick=()=>{const s=slides[current];$('motionTitle').textContent=s.title;$('motionDesc').textContent=descriptions[s.media];$('player').poster=`media/${s.media}-poster.png`;$('player').src=`media/${s.media}.mp4`;$('staticLink').href=`media/${s.media}-poster.png`;$('staticLink').textContent='View the static PNG alternative';$('motion').showModal()};$('closeMotion').onclick=()=>{$('player').pause();$('motion').close()};$('motion').addEventListener('close',()=>{$('player').pause()});document.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if($('motion').open)return;if(e.key==='ArrowRight'||e.key==='PageDown')show(current+1);if(e.key==='ArrowLeft'||e.key==='PageUp')show(current-1);if(e.key.toLowerCase()==='n')$('notesBtn').click();if(e.key.toLowerCase()==='p')$('present').click();if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1)});show(Math.max(0,(parseInt(location.hash.slice(1))||1)-1));
</script></body></html>'''
page=page.replace('SLIDE_DATA',js)

(out/'index.html').write_text(page)
(out/'deck-data.json').write_text(json.dumps(data,indent=2,ensure_ascii=False))
print('Offline browser deck authored:',out/'index.html')
